local gui_controls = require('main/gui_controls')

function init(self)
	msg.post('.', 'acquire_input_focus')
	msg.post('#', 'hide_level_select')
	self.active = false

	self.buttons = {}
	self.selected_index = 1
	for n = 1, _G.LEVEL_COUNT do
		local node_id = 'level_' .. n .. '_btn/button_box'
		self.buttons[n] = gui.get_node(node_id)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash('show_level_select') then
		msg.post('#', 'enable')
		self.active = true
		-- Stop LEVEL music, not menu music
		msg.post('main:/sounds', 'stop_music')

		gui_controls.navigate(self, 0, gui)

	elseif message_id == hash('hide_level_select') then
		msg.post('#', 'disable')
		self.active = false
		msg.post('main:/sounds', 'play_music')
		msg.post('main:/sounds', 'stop_menu_music')

	elseif message_id == hash('levels_data') then
		self.levels_data = message.levels_data
	end
end

function on_input(self, action_id, action)
	if self.active then
		if action_id == hash('touch') and action.pressed then
			for i = 1, _G.LEVEL_COUNT do
				local node = gui.get_node('level_' .. i .. '_btn/button_box')
				local level_data = self.levels_data['level_' .. i]
				if level_data.unlocked then
					if gui.pick_node(node, action.x, action.y) then
						msg.post('main:/sounds', 'play_button_sound')
						msg.post('/loader', 'load_level', { level = i })
						msg.post('#', 'hide_level_select')
					end
				end
			end
			
		elseif action_id == hash('Menu') then
			msg.post('#', 'disable')
			msg.post('/guis', 'show_start_menu')
		
		elseif action_id == hash('Up') and (action.pressed or action.repeated) then
			gui_controls.navigate(self, -2, gui)
			msg.post('main:/sounds', 'play_cursor_sound')
			
		elseif action_id == hash('Down') and (action.pressed or action.repeated) then
			gui_controls.navigate(self, 2, gui)
			msg.post('main:/sounds', 'play_cursor_sound')
			
		elseif action_id == hash('Left') and (action.pressed or action.repeated) then
			gui_controls.navigate(self, -1, gui)
			msg.post('main:/sounds', 'play_cursor_sound')
			
		elseif action_id == hash('Right') and (action.pressed or action.repeated) then
			gui_controls.navigate(self, 1, gui)
			msg.post('main:/sounds', 'play_cursor_sound')

		elseif action_id == hash('Interact') and action.pressed then
			local level_data = self.levels_data['level_' .. self.selected_index]
			if level_data.unlocked then
				msg.post('/loader', 'load_level', { level = self.selected_index })
				msg.post('#', 'hide_level_select')
			end
		end
	end
end
