local level_exit_helpers = require('main/level_exit/level_exit_helpers')

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") and message.other_group == hash("player") then
		local level_exit_url = level_exit_helpers.get_level_exit_url(go, _G.LEVEL_COUNT)
		msg.post(level_exit_url, 'key_picked_up')
		msg.post('main:/sounds', 'play_powerup_pickup')
		go.delete()
	end
end