function init(self)
	msg.post('#', 'show_start_menu')
	self.active = false
end

function on_message(self, message_id, message, sender)
	if message_id == hash('show_start_menu') then
		msg.post('#', 'enable')
		self.active = true
		msg.post('main:/sounds', 'stop_music')
	elseif message_id == hash('hide_start_menu') then
		msg.post('#', 'disable')
		self.active = false
	end
end

function on_input(self, action_id, action)
	if self.active then
		if action_id == hash('touch') and action.pressed then
			local start = gui.get_node('start_button/button_box')
			if gui.pick_node(start, action.x, action.y) then
				msg.post('#', 'hide_start_menu')
				msg.post('#level_select', 'show_level_select')
				msg.post('main:/sounds', 'play_button_sound')
			end

		elseif action_id == hash('Interact') and action.pressed then
			msg.post('#', 'hide_start_menu')
			msg.post('#level_select', 'show_level_select')
			msg.post('main:/sounds', 'play_button_sound')
		end
	end
end
