components {
  id: "track"
  component: "/main/tracks/track.script"
}
embedded_components {
  id: "track_sprite"
  type: "sprite"
  data: "default_animation: \"turn\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/tracks/tracks.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "track_collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"track_trigger\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 2.0\n"
  "      y: -6.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -8.0\n"
  "      y: 7.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.70710677\n"
  "      w: 0.70710677\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 2.2837424\n"
  "  data: 14.6316395\n"
  "  data: 10.0\n"
  "  data: 2.0559075\n"
  "  data: 11.904305\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
